### ISSUE TITLE
Insert/Update progress

### ISSUE THREAD

**Issue by MostHated** [nodew/PwSafeClient#1]
Hey there,
    Was just wondering if any progress has been made on the update/inserting of passwords? 

Thanks,
-MH

**Comment by nodew** [comment]
I'm thinking about to replace the low-level pwsafe encode/decode library to [PasswordSafe](https://www.nuget.org/packages/PasswordSafe), don't have time to make the changes yet.

**Comment by nodew** [comment]
Related commands have been added.
